### ISSUE TITLE
Self-host VFX

### ISSUE THREAD

**Issue by zackschuster** [zackschuster/vfx#10]
Pros:
a) Self-hosting is cool & good, and
b) You'd get a performance boost from removing `require()` calls

Cons:
a) SystemJS doesn't play well with node's DI (the builder errors if you point it at a file with a `require` in it), so I'd need to build in some way of packaging dependencies (Though as a pleasant side-effect, this might lead to me being able to deprecate the internal database).
b) It will take effort :cry:

:

**Comment by ledge23** [comment]
The internal library has been deprecated as of 936ac6bcc7f9aecfe46a7e3268f137f034611605. Hooray! This should make it long-run easier to self-host.
