### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by zackschuster** [zackschuster/vfx#5]
Confession: To date, I've written a grand total of 0 (zero) unit tests (bad Zack, bad!)

Four out of five experts agree that unit tests are important¹, so I'm taking this as a learning opportunity to get into an aspect of development that I've been putting off. And I mean, really, this whole project is basically a Hot Wheels race track of a learning opportunity (_zooms through loops_), so might as well make the most of it!

As a point of clarification, I've tagged this `help wanted` because my extreme level of ignorance here makes me wary of the quality of test coverage I'll produce, even if just initially. Any kind of advice or resource sharing would be much appreciated.

As far as what I'll be using for testing, I'm currently looking at using [AVA](https://github.com/sindresorhus/ava), because @sindresorhus is awesome and writing tests in es6 is A Nice.

---

¹The fifth expert was [bitten by a squirrel](https://www.youtube.com/watch?v=tXqAyMhgc7I).

**Comment by ledge23** [comment]
***Update*** I've started adding unit tests with AVA. As soon as I have all the files covered with appropriate tests, I'll close this issue; this might take a week or two, depending on the time I have.

**Comment by ledge23** [comment]
Travis-CI and Coveralls are now up-and-running. Hooray!

**Comment by ledge23** [comment]
Files left to test:
- [ ] `lib/builder.js`
- [ ] `lib/compiler.js`
- [ ] `lib/config/system.js`
- [ ] `lib/modules/database.js`

**Comment by zackschuster** [comment]
made a big push with this tonight & nearly have it finished. last two files are `lib/compiler/bundler.js` and `lib/compiler/compiler.js` and i'll have the entire app tested. 

well, except for `lib/index.js`, but a) that'll need to be rewritten for testability, and b) it's mainly just orchestrating the app, so the need for testing it (imo) is low enough that it's non-blocking for closing this issue.

with the current architecture in place, i don't expect there to be much (if any) file churn that would set this back anymore.
